import type { WorkflowCheckpointCatalogEntry } from "./contracts.js";

export const WORKFLOW_CHECKPOINT_CATALOG: readonly WorkflowCheckpointCatalogEntry[] = [
  {
    checkpoint: "candidate_selection_required",
    displayStage: "project_setup",
    workflowStage: "auto_director",
    tab: "basic",
    label: "等待确认书级方向",
    approvalPoint: "candidate_direction_confirmed",
    defaultProgress: 0.18,
  },
  {
    checkpoint: "book_contract_ready",
    displayStage: "story_planning",
    workflowStage: "story_macro",
    tab: "story_macro",
    label: "书级规划已就绪",
    approvalPoint: null,
    defaultProgress: 0.42,
  },
  {
    checkpoint: "character_setup_required",
    displayStage: "character_setup",
    workflowStage: "character_setup",
    tab: "character",
    label: "角色准备待确认",
    approvalPoint: "character_setup_ready",
    defaultProgress: 0.52,
  },
  {
    checkpoint: "volume_strategy_ready",
    displayStage: "volume_strategy",
    workflowStage: "volume_strategy",
    tab: "outline",
    label: "卷战略已就绪",
    approvalPoint: "volume_strategy_ready",
    defaultProgress: 0.62,
  },
  {
    checkpoint: "chapter_batch_ready",
    displayStage: "structured_outline",
    workflowStage: "chapter_execution",
    tab: "chapter",
    label: "章节执行可继续",
    waitingApprovalLabel: "节奏拆章完成，可进入章节执行",
    pausedLabel: "自动执行已暂停",
    approvalPoint: "structured_outline_ready",
    defaultProgress: 0.9,
  },
  {
    checkpoint: "step_review_required",
    displayStage: "story_planning",
    workflowStage: "auto_director",
    tab: "pipeline",
    label: "步骤已生成，等待检查",
    waitingApprovalLabel: "当前步骤已完成，请检查后继续",
    pausedLabel: "逐步协作已暂停",
    approvalPoint: null,
    defaultProgress: 0.5,
  },
  {
    checkpoint: "replan_required",
    displayStage: "quality_repair",
    workflowStage: "quality_repair",
    tab: "pipeline",
    label: "需要处理质量修复",
    approvalPoint: "replan_continue",
    defaultProgress: 0.97,
  },
  {
    checkpoint: "workflow_completed",
    displayStage: "quality_repair",
    workflowStage: "quality_repair",
    tab: "pipeline",
    label: "导演主流程已完成",
    approvalPoint: null,
    defaultProgress: 1,
  },
  {
    checkpoint: "rewrite_snapshot_created",
    displayStage: "project_setup",
    workflowStage: "auto_director",
    tab: "basic",
    label: "重写前备份已创建",
    approvalPoint: "rewrite_cleanup_confirmed",
    defaultProgress: 0.1,
  },
] as const;
