import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { z } from "zod";
import type { PromptAsset } from "../../../core/promptTypes";
import type {
  WorldDeepeningQuestionsPromptInput,
  WorldConsistencyPromptInput,
} from "../world.promptTypes";
import {
  worldDeepeningQuestionsSchema,
  worldConsistencyIssuesSchema,
} from "../world.promptSchemas";

export const worldDeepeningQuestionsPrompt: PromptAsset<
  WorldDeepeningQuestionsPromptInput,
  z.infer<typeof worldDeepeningQuestionsSchema>
> = {
  id: "world.deepening.questions",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldDeepeningQuestionsSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观补全提问器。",
      "你的任务是基于当前世界设定，挑出最值得优先追问的 2-3 个关键补全问题，帮助后续世界生成继续往下走。",
      "",
      "只输出一个合法 JSON 数组，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "",
      "每个数组项必须严格使用以下结构：",
      "{",
      '  "priority":"required|recommended|optional",',
      '  "question":"...",',
      '  "quickOptions":["...", "...", "..."],',
      '  "targetLayer":"foundation|power|society|culture|history|conflict",',
      '  "targetField":"..."',
      "}",
      "",
      "全局硬规则：",
      "1. 只能输出 2-3 个问题，不得少于 2 个，不得多于 3 个。",
      "2. 所有文本必须使用简体中文。",
      "3. 只能基于输入中的世界名称、描述、已有数据和可用参考素材来提问，不得凭空发散到无关方向。",
      "4. 问题必须是“继续生成世界前最值得先问的缺口”，而不是泛泛聊天问题。",
      "",
      "问题设计要求：",
      "1. 每个问题都必须指向一个真正会影响后续世界搭建方向的关键缺口。",
      "2. 优先提问最能决定世界走向、规则形态、社会结构、冲突来源或历史底板的问题。",
      "3. 不要问太宽的问题，例如“你还想补充什么”“这个世界还有什么特点”。",
      "4. 不要问角色动机、具体剧情桥段、感情推进这类故事层问题，除非它直接影响世界层结构。",
      "",
      "priority 规则：",
      "1. required：缺了这个问题，后续世界生成容易跑偏或塌掉。",
      "2. recommended：补上会明显提升世界完整度与可写性，但短期缺失仍可继续。",
      "3. optional：属于锦上添花型补充，不是当前最硬缺口。",
      "",
      "question 规则：",
      "1. 必须写成用户一看就能回答的自然问题。",
      "2. 问法要具体、清楚，不要用抽象术语。",
      "3. 每个问题都应尽量只问一个核心点，不要把多个问题塞进一句话。",
      "",
      "quickOptions 规则：",
      "1. 必须提供 2-4 个简洁候选答案，全部使用简体中文。",
      "2. quickOptions 应该帮助用户快速选择方向，而不是重复 question。",
      "3. 不同选项之间必须体现真实分叉，不能只是同义改写。",
      "4. 选项要短、准、可直接点选，不要写成长句分析。",
      "",
      "targetLayer 规则：",
      "1. 只能从 foundation、power、society、culture、history、conflict 中选择。",
      "2. 必须准确对应这个问题主要作用于哪一层世界结构。",
      "",
      "targetField 规则：",
      "1. 必须写清这个问题要补的是哪个具体字段或决策点。",
      "2. targetField 要简洁稳定，适合后续系统消费，例如“规则公开程度”“力量来源”“社会控制方式”“历史断层原因”。",
      "",
      "选择优先级原则：",
      "1. 优先挑“最少提问、最大增益”的问题。",
      "2. 若已有 dataJson 已经较完整，就不要重复问已明确的信息。",
      "3. 若 ragContext 提供了强参考方向，可以优先追问那些会决定参考素材如何落地的关键分叉。",
      "4. 2-3 个问题之间尽量分布在不同层级，不要全部挤在同一层，除非某一层确实是当前最大缺口。",
      "",
      "质量要求：",
      "1. 输出的问题要让用户感觉“这几个问题确实问到了点子上”。",
      "2. 不要为了凑数量提价值很低的问题。",
      "3. 整体结果必须能直接用于下一步世界补全流程。",
    ].join("\n")),
    new HumanMessage([
      `世界名称：${input.worldName}`,
      `世界描述：${input.description || "无"}`,
      `当前数据：${input.dataJson}`,
      `可用参考素材：${input.ragContext || "无"}`,
    ].join("\n")),
  ],
};

export const worldConsistencyPrompt: PromptAsset<
  WorldConsistencyPromptInput,
  z.infer<typeof worldConsistencyIssuesSchema>
> = {
  id: "world.consistency.check",
  version: "v1",
  taskType: "review",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldConsistencyIssuesSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观一致性审校器。",
      "你的任务是检查当前世界设定是否存在明确冲突、规则打架或高风险不一致点，并输出结构化问题列表。",
      "",
      "只输出一个合法 JSON 数组，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "如果没有问题，只输出 []。",
      "",
      "每项结构必须严格为：",
      '{"severity":"warn|error","code":"...","message":"中文问题概述","detail":"中文详细说明","targetField":"description|background|geography|cultures|magicSystem|politics|races|religions|technology|conflicts|history|economy|factions"}',
      "",
      "全局硬规则：",
      "1. message 和 detail 必须使用简体中文。",
      "2. 只能基于给定世界公理、核心设定和检索补充进行判断，不得脑补未提供的设定。",
      "3. 只指出真正的冲突或明显风险，不要泛泛而谈，不要为了凑数量制造问题。",
      "4. 如果证据不足，不要强行判定为问题。",
      "",
      "审校重点：",
      "1. 世界公理与具体设定是否冲突。",
      "2. 不同字段之间是否存在规则打架、因果断裂或层级不兼容。",
      "3. 设定是否会导致明显不可运行、不可持续或互相抵消的结构风险。",
      "4. 地理、政治、经济、宗教、种族、技术、魔法、历史、冲突体系之间是否存在显著不自洽。",
      "",
      "severity 规则：",
      "1. error：存在明确冲突、无法同时成立、或会直接破坏世界运行逻辑的问题。",
      "2. warn：当前未必绝对冲突，但存在明显高风险、解释缺口或后续极易写崩的点。",
      "",
      "字段要求：",
      "1. code：使用简洁稳定、可复用的英文或下划线风格问题编码，不要写成长句。",
      "2. message：一句话点明问题核心，让人一眼看懂哪里冲突。",
      "3. detail：具体说明为什么这是问题，冲突发生在哪两层或哪几个字段之间。",
      "4. targetField：必须从以下字段中选择最主要的问题落点：description、background、geography、cultures、magicSystem、politics、races、religions、technology、conflicts、history、economy、factions。",
      "",
      "质量要求：",
      "1. 优先输出最关键、最会影响后续世界生成和写作的问题。",
      "2. 若多个问题本质相同，应合并，不要重复报同一类风险。",
      "3. detail 必须具体，不能只重复 message。",
      "4. 输出结果必须可直接供后续修正流程使用。",
    ].join("\n")),
    new HumanMessage([
      `世界名：${input.worldName}`,
      `世界公理：${input.axioms || "无"}`,
      `核心设定：${input.coreSettingsJson}`,
      `检索补充：${input.ragContext || "无"}`,
    ].join("\n")),
  ],
};
