import type { Chapter } from "@novelfoundry/shared/types/novel";
import type { QuickCharacterCreatePayload } from "../../../components/characterPanel.utils";
import type { ChapterExecutionStrategy } from "../../../chapterExecution.utils";
import type { useNovelEditWorkspaceState } from "../../hooks/useNovelEditWorkspaceState";
import type { useNovelEditWorkspaceData } from "../../hooks/useNovelEditWorkspaceData";
import type { useNovelEditProductionRuntime } from "../../hooks/production/useNovelEditProductionRuntime";
import type { useNovelEditDirectorProjection } from "../../hooks/director/useNovelEditDirectorProjection";

interface BuildNovelEditWorkspaceProductionTabsInput {
  state: ReturnType<typeof useNovelEditWorkspaceState>;
  data: ReturnType<typeof useNovelEditWorkspaceData>;
  production: ReturnType<typeof useNovelEditProductionRuntime>;
  director: ReturnType<typeof useNovelEditDirectorProjection>;
}

export function buildNovelEditWorkspaceProductionTabs({
  state,
  data,
  production,
  director,
}: BuildNovelEditWorkspaceProductionTabsInput) {
  const {
    setActiveTab,
    id,
    selectedChapterId,
    setSelectedChapterId,
    chapterOperationMessage,
    chapterStrategy,
    setChapterStrategy,
    reviewResult,
    activeRepairStream,
    activeChapterStream,
    pipelineForm,
    setPipelineForm,
    llm,
    pipelineMessage,
    setRepairBeforeContent,
    setRepairAfterContent,
    setActiveRepairStream,
    repairBeforeContent,
    repairAfterContent,
    characterMessage,
    quickCharacterForm,
    setQuickCharacterForm,
    selectedBaseCharacterId,
    setSelectedBaseCharacterId,
    selectedCharacterId,
    setSelectedCharacterId,
    characterForm,
    setCharacterForm,
  } = state;
  const {
    worldInjectionSummary,
    hasCharacters,
    chapters,
    selectedChapter,
    chapterPlan,
    latestStateSnapshot,
    chapterStateSnapshot,
    chapterTimeline,
    chapterTimelineQuery,
    chapterResourceContext,
    chapterResourceContextQuery,
    chapterPendingCharacterResourceProposals,
    chapterAuditReports,
    pipelineBackgroundActivities,
    chapterQualityReport,
    maxOrder,
    pipelineJobQuery,
    openAuditIssueIds,
    qualitySummary,
    qualityReportQuery,
    bible,
    plotBeats,
    characters,
    coreCharacterCount,
    baseCharacters,
    selectedBaseCharacter,
    importedBaseCharacterIds,
    selectedCharacter,
    characterResources,
    pendingCharacterResourceProposals,
  } = data;
  const {
    createChapterMutation,
    deleteManualChapterMutation,
    chapterExecutionActions,
    handleGenerateSelectedChapter,
    generateChapterPlanMutation,
    replanChapterMutation,
    runChapterReview,
    reviewActionKind,
    fullAuditMutation,
    repairSSE,
    extractChapterResourcesMutation,
    confirmCharacterResourceProposalMutation,
    rejectCharacterResourceProposalMutation,
    chapterSSE,
    handleAbortRepair,
    handleAbortChapterStream,
    bibleSSE,
    beatsSSE,
    runPipelineMutation,
    reviewMutation,
    hookMutation,
    quickCreateCharacterMutation,
    generateSupplementalCharacterMutation,
    applySupplementalCharacterMutation,
    importBaseCharacterMutation,
    deleteCharacterMutation,
    syncTimelineMutation,
    syncAllTimelineMutation,
    evolveCharacterMutation,
    generateVisibleProfileMutation,
    applyVisibleProfileMutation,
    generateBatchVisibleProfilesMutation,
    applyBatchVisibleProfilesMutation,
    worldCheckMutation,
    backfillCharacterResourcesMutation,
    saveCharacterMutation,
    characterTimelineQuery,
  } = production;
  const { activeDirectorSession } = director;
  const goToCharacterTab = () => setActiveTab("character");
  const chapterTab = {
    novelId: id,
    worldInjectionSummary,
    hasCharacters,
    chapters,
    selectedChapterId,
    selectedChapter,
    onSelectChapter: setSelectedChapterId,
    onGoToCharacterTab: goToCharacterTab,
    onCreateChapter: () => createChapterMutation.mutate(),
    isCreatingChapter: createChapterMutation.isPending,
    onRemoveChapter: (chapter: Chapter) => {
      const confirmed = window.confirm(`确认移除「第${chapter.order}章 ${chapter.title || "未命名章节"}」吗？该章节尚未开始写作，移除后不可恢复。`);
      if (confirmed) {
        deleteManualChapterMutation.mutate(chapter.id);
      }
    },
    removingChapterId: deleteManualChapterMutation.isPending
      ? deleteManualChapterMutation.variables ?? null
      : null,
    chapterOperationMessage,
    strategy: chapterStrategy,
    onStrategyChange: (field: "runMode" | "wordSize" | "conflictLevel" | "pace" | "aiFreedom", value: string | number) =>
      setChapterStrategy((prev) => ({ ...prev, [field]: value } as ChapterExecutionStrategy)),
    onApplyStrategy: chapterExecutionActions.applyStrategy,
    isApplyingStrategy: chapterExecutionActions.isPatchingChapter,
    onGenerateSelectedChapter: handleGenerateSelectedChapter,
    onRewriteChapter: chapterExecutionActions.rewriteChapter,
    onExpandChapter: chapterExecutionActions.expandChapter,
    onCompressChapter: chapterExecutionActions.compressChapter,
    onSummarizeChapter: chapterExecutionActions.summarizeChapter,
    onGenerateTaskSheet: chapterExecutionActions.generateTaskSheet,
    onGenerateSceneCards: chapterExecutionActions.generateSceneCards,
    onGenerateChapterPlan: () => generateChapterPlanMutation.mutate(),
    onReplanChapter: () => replanChapterMutation.mutate(),
    onRunFullAudit: () => runChapterReview("full_audit"),
    onCheckContinuity: chapterExecutionActions.checkContinuity,
    onCheckCharacterConsistency: chapterExecutionActions.checkCharacterConsistency,
    onCheckPacing: chapterExecutionActions.checkPacing,
    onAutoRepair: chapterExecutionActions.autoRepair,
    onStrengthenConflict: chapterExecutionActions.strengthenConflict,
    onEnhanceEmotion: chapterExecutionActions.enhanceEmotion,
    onUnifyStyle: chapterExecutionActions.unifyStyle,
    onAddDialogue: chapterExecutionActions.addDialogue,
    onAddDescription: chapterExecutionActions.addDescription,
    isGeneratingTaskSheet: chapterExecutionActions.isGeneratingTaskSheet,
    isGeneratingSceneCards: chapterExecutionActions.isGeneratingSceneCards,
    isSummarizingChapter: chapterExecutionActions.isSummarizingChapter,
    reviewActionKind,
    repairActionKind: chapterExecutionActions.repairActionKind,
    generationActionKind: chapterExecutionActions.generationActionKind,
    isReviewingChapter: fullAuditMutation.isPending,
    isRepairingChapter: repairSSE.isStreaming,
    reviewResult,
    replanRecommendation: reviewResult?.replanRecommendation ?? null,
    lastReplanResult: replanChapterMutation.data?.data ?? null,
    chapterPlan,
    latestStateSnapshot,
    chapterStateSnapshot,
    chapterTimeline,
    isLoadingChapterTimeline: chapterTimelineQuery.isLoading || chapterTimelineQuery.isFetching,
    chapterResourceContext,
    isLoadingChapterResourceContext: chapterResourceContextQuery.isLoading || chapterResourceContextQuery.isFetching,
    resourceWorkflowMode: activeDirectorSession ? ("auto_director" as const) : ("manual" as const),
    pendingCharacterResourceProposals: chapterPendingCharacterResourceProposals,
    onExtractChapterResources: () => extractChapterResourcesMutation.mutate(),
    isExtractingChapterResources: extractChapterResourcesMutation.isPending,
    onConfirmCharacterResourceProposal: (proposalId: string) => confirmCharacterResourceProposalMutation.mutate(proposalId),
    onRejectCharacterResourceProposal: (proposalId: string) => rejectCharacterResourceProposalMutation.mutate(proposalId),
    confirmingCharacterResourceProposalId: confirmCharacterResourceProposalMutation.isPending
      ? confirmCharacterResourceProposalMutation.variables ?? ""
      : "",
    rejectingCharacterResourceProposalId: rejectCharacterResourceProposalMutation.isPending
      ? rejectCharacterResourceProposalMutation.variables ?? ""
      : "",
    chapterAuditReports,
    backgroundSyncActivities: pipelineBackgroundActivities,
    isGeneratingChapterPlan: generateChapterPlanMutation.isPending,
    isReplanningChapter: replanChapterMutation.isPending,
    isRunningFullAudit: fullAuditMutation.isPending && reviewActionKind === "full_audit",
    chapterQualityReport,
    chapterRuntimePackage: chapterSSE.runtimePackage,
    repairStreamContent: repairSSE.content,
    isRepairStreaming: repairSSE.isStreaming,
    repairStreamingChapterId: activeRepairStream?.chapterId ?? null,
    repairStreamingChapterLabel: activeRepairStream?.chapterLabel ?? null,
    repairRunStatus: repairSSE.latestRun,
    onAbortRepair: handleAbortRepair,
    streamContent: chapterSSE.content,
    isStreaming: chapterSSE.isStreaming,
    streamingChapterId: activeChapterStream?.chapterId ?? null,
    streamingChapterLabel: activeChapterStream?.chapterLabel ?? null,
    chapterRunStatus: chapterSSE.latestRun,
    onAbortStream: handleAbortChapterStream,
    directorTakeoverEntry: undefined,
  };
  const pipelineTab = {
    novelId: id,
    worldInjectionSummary,
    hasCharacters,
    onGoToCharacterTab: goToCharacterTab,
    pipelineForm,
    onPipelineFormChange: (field: "startOrder" | "endOrder" | "maxRetries" | "runMode" | "autoReview" | "autoRepair" | "skipCompleted" | "qualityThreshold" | "repairMode", value: number | boolean | string) => setPipelineForm((prev) => ({ ...prev, [field]: value } as typeof prev)),
    maxOrder,
    onGenerateBible: () => void bibleSSE.start(`/novels/${id}/bible/generate`, { provider: llm.provider, model: llm.model, temperature: 0.6 }),
    onAbortBible: bibleSSE.abort,
    isBibleStreaming: bibleSSE.isStreaming,
    bibleStreamContent: bibleSSE.content,
    onGenerateBeats: () => void beatsSSE.start(`/novels/${id}/beats/generate`, { provider: llm.provider, model: llm.model, targetChapters: pipelineForm.endOrder }),
    onAbortBeats: beatsSSE.abort,
    isBeatsStreaming: beatsSSE.isStreaming,
    beatsStreamContent: beatsSSE.content,
    onRunPipeline: (patch?: Partial<typeof pipelineForm>) => runPipelineMutation.mutate(patch),
    isRunningPipeline: runPipelineMutation.isPending,
    pipelineMessage,
    pipelineJob: pipelineJobQuery.data?.data,
    chapters,
    selectedChapterId,
    onSelectedChapterChange: setSelectedChapterId,
    onReviewChapter: () => reviewMutation.mutate(),
    isReviewing: reviewMutation.isPending,
    onRepairChapter: () => {
      setRepairBeforeContent(selectedChapter?.content ?? "");
      setRepairAfterContent("");
      setActiveRepairStream(selectedChapter ? {
        chapterId: selectedChapter.id,
        chapterLabel: `第${selectedChapter.order}章 ${selectedChapter.title || "未命名章节"}`
      } : null);
      void repairSSE.start(`/novels/${id}/chapters/${selectedChapterId}/repair`, {
        provider: llm.provider,
        model: llm.model,
        reviewIssues: reviewResult?.issues ?? [],
        auditIssueIds: openAuditIssueIds
      });
    },
    isRepairing: repairSSE.isStreaming,
    onGenerateHook: () => hookMutation.mutate(),
    isGeneratingHook: hookMutation.isPending,
    reviewResult,
    repairBeforeContent,
    repairAfterContent,
    repairStreamContent: repairSSE.content,
    isRepairStreaming: repairSSE.isStreaming,
    onAbortRepair: handleAbortRepair,
    qualitySummary,
    chapterReports: qualityReportQuery.data?.data?.chapterReports ?? [],
    bible,
    plotBeats
  };
  const characterTab = {
    novelId: id,
    llmProvider: llm.provider,
    llmModel: llm.model,
    characterMessage,
    quickCharacterForm,
    onQuickCharacterFormChange: (field: "name" | "role", value: string) =>
      setQuickCharacterForm((prev) => ({ ...prev, [field]: value })),
    onQuickCreateCharacter: (payload: QuickCharacterCreatePayload) => quickCreateCharacterMutation.mutate(payload),
    isQuickCreating: quickCreateCharacterMutation.isPending,
    onGenerateSupplementalCharacters: generateSupplementalCharacterMutation.mutateAsync,
    isGeneratingSupplementalCharacters: generateSupplementalCharacterMutation.isPending,
    onApplySupplementalCharacter: applySupplementalCharacterMutation.mutateAsync,
    isApplyingSupplementalCharacter: applySupplementalCharacterMutation.isPending,
    characters,
    coreCharacterCount,
    baseCharacters,
    selectedBaseCharacterId,
    onSelectedBaseCharacterChange: setSelectedBaseCharacterId,
    selectedBaseCharacter,
    importedBaseCharacterIds,
    onImportBaseCharacter: () => importBaseCharacterMutation.mutate(),
    isImportingBaseCharacter: importBaseCharacterMutation.isPending,
    selectedCharacterId,
    onSelectedCharacterChange: setSelectedCharacterId,
    onDeleteCharacter: (characterId: string) => deleteCharacterMutation.mutate(characterId),
    isDeletingCharacter: deleteCharacterMutation.isPending,
    deletingCharacterId: deleteCharacterMutation.variables ?? "",
    onSyncTimeline: () => syncTimelineMutation.mutate(),
    isSyncingTimeline: syncTimelineMutation.isPending,
    onSyncAllTimeline: () => syncAllTimelineMutation.mutate(),
    isSyncingAllTimeline: syncAllTimelineMutation.isPending,
    onEvolveCharacter: () => evolveCharacterMutation.mutate(),
    isEvolvingCharacter: evolveCharacterMutation.isPending,
    onGenerateVisibleProfile: (userGuidance?: string) => generateVisibleProfileMutation.mutate(userGuidance),
    isGeneratingVisibleProfile: generateVisibleProfileMutation.isPending,
    visibleProfileSuggestion: generateVisibleProfileMutation.data?.data ?? null,
    onApplyVisibleProfile: () => applyVisibleProfileMutation.mutate(),
    isApplyingVisibleProfile: applyVisibleProfileMutation.isPending,
    onGenerateBatchVisibleProfiles: (userGuidance?: string) => generateBatchVisibleProfilesMutation.mutate(userGuidance),
    isGeneratingBatchVisibleProfiles: generateBatchVisibleProfilesMutation.isPending,
    batchVisibleProfileResult: generateBatchVisibleProfilesMutation.data?.data ?? null,
    onApplyBatchVisibleProfiles: () => applyBatchVisibleProfilesMutation.mutate(),
    isApplyingBatchVisibleProfiles: applyBatchVisibleProfilesMutation.isPending,
    onWorldCheck: () => worldCheckMutation.mutate(),
    isCheckingWorld: worldCheckMutation.isPending,
    selectedCharacter,
    characterResources,
    pendingCharacterResourceCount: pendingCharacterResourceProposals.length,
    onBackfillCharacterResources: () => backfillCharacterResourcesMutation.mutate(),
    isBackfillingCharacterResources: backfillCharacterResourcesMutation.isPending,
    characterForm,
    onCharacterFormChange: (field: keyof typeof characterForm, value: string) =>
      setCharacterForm((prev) => ({ ...prev, [field]: value })),
    onSaveCharacter: () => saveCharacterMutation.mutate(),
    isSavingCharacter: saveCharacterMutation.isPending,
    timelineEvents: characterTimelineQuery.data?.data ?? [],
  };
  return {
    chapterTab,
    pipelineTab,
    characterTab,
  };
}
